name: Keep AstraDB Active

on:
  schedule:
    # Run every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  ping-chatbot:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to chatbot
        run: |
          echo "Run started at: $(date -u)"

          STATUS=$(curl -s -o /dev/null -L \
            --connect-timeout 5 \
            --max-time 10 \
            -w "%{http_code}" \
            -X POST "https://connorhyatt.com/api/chat" \
            -H "Content-Type: application/json" \
            -d '{"messages":[{"role":"user","content":"ping"}]}')

          echo "HTTP Status: $STATUS"

          if [ "$STATUS" -ne 200 ]; then
            echo "❌ Chatbot request failed with status $STATUS"
            exit 1
          fi

          echo "Run finished at: $(date -u)"
