name: Keep AstraDB Active

on:
  schedule:
    # Run every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  ping-chatbot:
    runs-on: ubuntu-latest
    steps:
      - name: Ping AstraDB via chatbot /api/ping
        run: |
          echo "Run started at: $(date -u)"

          STATUS=$(curl -s -o /dev/null -L \
            --connect-timeout 5 \
            --max-time 20 \
            -w "%{http_code}" \
            -X POST "https://connorhyatt.com/api/ping" \
            -H "Content-Type: application/json")

          echo "HTTP Status: $STATUS"

          if [ "$STATUS" -ne 200 ]; then
            echo "❌ Ping failed with status $STATUS"
            exit 1
          fi

          echo "✅ AstraDB kept alive successfully"
          echo "Run finished at: $(date -u)"
