name: Keep AstraDB Active

on:
  schedule:
    # Run every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # allows manual trigger

jobs:
  ping-chatbot:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to chatbot
        run: |
          curl -X POST "https://connorhyatt.com/api/chat" \
            -H "Content-Type: application/json" \
            -d '{
              "messages": [
                {
                  "role": "user", 
                  "content": "hello"
                }
              ]
            }'
