name: Keep AstraDB Awake

on:
  schedule:
    # Run twice daily at 6 AM and 6 PM UTC to prevent hibernation
    - cron: '0 6,18 * * *'
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  ping-astra:
    runs-on: ubuntu-latest
    steps:
      - name: Ping AstraDB endpoint
        run: |
          curl -X POST "https://connorhyatt.com/api/ping" \
            -H "Content-Type: application/json" \
            --fail --silent --show-error
        continue-on-error: true

      - name: Log ping attempt
        run: echo "AstraDB ping completed at $(date)"
